<a href="https://colab.research.google.com/github/flyingrockingit/Module-11/blob/main/LogisticRegressionProject.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

x = np.arange(10).reshape(-1, 1)
y = np.array([0, 0, 0, 0, 1, 1, 1, 1, 1, 1])

model = LogisticRegression(solver='liblinear', random_state=0)
model.fit(x, y)

p_pred = model.predict_proba(x)
y_pred = model.predict(x)

score = model.score(x, y)
conf_matrix = confusion_matrix(y, y_pred)
class_report = classification_report(y, y_pred)

print("Predicted Probabilities:\n", p_pred)
print("\nPredicted Classes:\n", y_pred)
print("\nModel Accuracy:", score)
print("\nConfusion Matrix:\n", conf_matrix)
print("\nClassification Report:\n", class_report)

classes = np.unique(y)
print("\nClasses in dataset:", classes)

if len(classes) == 2:
    print("This dataset is Binary Classification")
else:
    print("This dataset is Multi-class Classification")


Predicted Probabilities:
 [[0.74002157 0.25997843]
 [0.62975524 0.37024476]
 [0.5040632  0.4959368 ]
 [0.37785549 0.62214451]
 [0.26628093 0.73371907]
 [0.17821501 0.82178499]
 [0.11472079 0.88527921]
 [0.07186982 0.92813018]
 [0.04422513 0.95577487]
 [0.02690569 0.97309431]]

Predicted Classes:
 [0 0 0 1 1 1 1 1 1 1]

Model Accuracy: 0.9

Confusion Matrix:
 [[3 1]
 [0 6]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.75      0.86         4
           1       0.86      1.00      0.92         6

    accuracy                           0.90        10
   macro avg       0.93      0.88      0.89        10
weighted avg       0.91      0.90      0.90        10


Classes in dataset: [0 1]
This dataset is Binary Classification
