<a href="https://colab.research.google.com/github/flyingrockingit/Module-11/blob/main/LogisticRegression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

x=np.arange(10).reshape(-1,1)
y=np.array([1,0,1,0,1,0,1,0,1,0])

model = LogisticRegression (solver='liblinear', random_state=0)
model.fit(x,y)

p_pred = model.predict_proba(x)
y_pred = model.predict(x)
score = model.score (x,y)
conf_metrix = confusion_matrix(y,y_pred)
class_report = classification_report(y,y_pred)

print(f"predicted probabilities\n{p_pred}")
print(f"predicted value classification\n{y_pred}")
print(f"Score:\n {score}")
print(f"confussion matrix\n{conf_metrix}")
print(f"Report:\n{class_report}")

predicted probabilities
[[0.44441544 0.55558456]
 [0.46167768 0.53832232]
 [0.4790323  0.5209677 ]
 [0.49643768 0.50356232]
 [0.5138517  0.4861483 ]
 [0.53123216 0.46876784]
 [0.54853717 0.45146283]
 [0.56572558 0.43427442]
 [0.58275736 0.41724264]
 [0.59959395 0.40040605]]
predicted value classification
[1 1 1 1 0 0 0 0 0 0]
Score:
 0.5
confussion matrix
[[3 2]
 [3 2]]
Report:
              precision    recall  f1-score   support

           0       0.50      0.60      0.55         5
           1       0.50      0.40      0.44         5

    accuracy                           0.50        10
   macro avg       0.50      0.50      0.49        10
weighted avg       0.50      0.50      0.49        10

